package tests

import (
	"flag"
	"net/http"
	"time"

	"bitbucket.org/emotech/common/golang/protos"
	"bitbucket.org/emotech/riemann/actuators/camera"
	"bitbucket.org/emotech/riemann/actuators/leds"
	micActuator "bitbucket.org/emotech/riemann/actuators/mic"
	"bitbucket.org/emotech/riemann/actuators/motors"
	"bitbucket.org/emotech/riemann/actuators/tts"
	"bitbucket.org/emotech/riemann/dolly"
	"bitbucket.org/emotech/riemann/iot/hass"
	"bitbucket.org/emotech/riemann/iot/lights"
	"bitbucket.org/emotech/riemann/loglines"
	"bitbucket.org/emotech/riemann/riemann"
	micSensor "bitbucket.org/emotech/riemann/sensors/mic"
	. "github.com/onsi/ginkgo"
	"github.com/onsi/gomega"
)

var dollyAddress = flag.String("dolly", "http://dolly:8080", "dolly address")

var _ = Describe("Riemann", func() {
	gomega.SetDefaultEventuallyTimeout(10. * time.Second)

	var olly *dolly.Dolly
	var r *riemann.Riemann
	BeforeSuite(func() {
		olly = dolly.NewDolly(*dollyAddress, &http.Client{})
		r = riemann.NewRiemann()
		r.Run()
		logger := loglines.NewLoggerWrapper(GinkgoWriter)
		logger.Start()
	})

	BeforeEach(func() {
		r.Restart(olly)
		r.WaitFor(olly).ToBe(riemann.StartedAndIdle())
	})

	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_on"),
			)
			r.Match( 
				riemann.Group( 
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					tts.Matcher("There is no light called like that"), 
				), 
			) 
		}) 
	}) 
	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_on"),
			)
			r.Match( 
				riemann.Group( 
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					tts.Matcher("turning the lights on"), 
				), 
			) 
		}) 
	}) 
	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_on"),
			)
			r.Match( 
				riemann.Group( 
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					tts.Matcher("There is no light called like that"), 
				), 
			) 
		}) 
	}) 
	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_on"),
			)
			r.Match( 
				riemann.Group( 
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					tts.Matcher("turning the lights on"), 
				), 
			) 
		}) 
	}) 
	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_on"),
				micSensor.Entities(
					"house_place","val"
				)
			)
			r.Match( 
				riemann.Group( 
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					tts.Matcher("There is no light called like that"), 
				), 
			) 
		}) 
	}) 
	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_on"),
				micSensor.Entities(
					"house_place","val"
				)
			)
			r.Match( 
				riemann.Group( 
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					tts.Matcher("turning the lights on"), 
				), 
			) 
		}) 
	}) 
	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_on"),
				micSensor.Entities(
					"house_place","val"
				)
			)
			r.Match( 
				riemann.Group( 
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					tts.Matcher("There is no light called like that"), 
				), 
			) 
		}) 
	}) 
	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_on"),
				micSensor.Entities(
					"house_place","val"
				)
			)
			r.Match( 
				riemann.Group( 
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					tts.Matcher("turning the lights on"), 
				), 
			) 
		}) 
	}) 
	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_on"),
				micSensor.Entities(
					"house_place","val"
				)
			)
			r.Match( 
				riemann.Group( 
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					tts.Matcher("There is no light called like that"), 
				), 
			) 
		}) 
	}) 
	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_on"),
				micSensor.Entities(
					"house_place","val"
				)
			)
			r.Match( 
				riemann.Group( 
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					tts.Matcher("turning the lights on"), 
				), 
			) 
		}) 
	}) 
	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_on"),
				micSensor.Entities(
					"house_place","val"
					"color","val"
				)
			)
			r.Match( 
				riemann.Group( 
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					tts.Matcher("There is no light called like that"), 
				), 
			) 
		}) 
	}) 
	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_on"),
				micSensor.Entities(
					"house_place","val"
					"color","val"
				)
			)
			r.Match( 
				riemann.Group( 
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					tts.Matcher("turning the lights on"), 
				), 
			) 
		}) 
	}) 
	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_on"),
				micSensor.Entities(
					"house_place","val"
					"color","val"
				)
			)
			r.Match( 
				riemann.Group( 
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					tts.Matcher("There is no light called like that"), 
				), 
			) 
		}) 
	}) 
	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_on"),
				micSensor.Entities(
					"house_place","val"
					"color","val"
				)
			)
			r.Match( 
				riemann.Group( 
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					tts.Matcher("turning the lights on"), 
				), 
			) 
		}) 
	}) 
	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_on"),
				micSensor.Entities(
					"house_place","val"
					"color","val"
				)
			)
			r.Match( 
				riemann.Group( 
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					tts.Matcher("There is no light called like that"), 
				), 
			) 
		}) 
	}) 
	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_on"),
				micSensor.Entities(
					"house_place","val"
					"color","val"
				)
			)
			r.Match( 
				riemann.Group( 
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("color","val")
							hass.Entity("entity_id","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					tts.Matcher("turning the lights on"), 
				), 
			) 
		}) 
	}) 
	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_up"),
			)
			r.Match( 
				riemann.Group( 
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					tts.Matcher("There is no light called like that"), 
				), 
			) 
		}) 
	}) 
	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_up"),
			)
			r.Match( 
				riemann.Group( 
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_name_and_capability", 
							hass.Entity("capability","val")
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					tts.Matcher("$error"), 
				), 
			) 
		}) 
	}) 
	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_up"),
			)
			r.Match( 
				riemann.Group( 
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_name_and_capability", 
							hass.Entity("capability","val")
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					tts.Matcher("brightening the lights"), 
				), 
			) 
		}) 
	}) 
	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_up"),
			)
			r.Match( 
				riemann.Group( 
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					tts.Matcher("There is no light called like that"), 
				), 
			) 
		}) 
	}) 
	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_up"),
			)
			r.Match( 
				riemann.Group( 
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_name_and_capability", 
							hass.Entity("capability","val")
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					tts.Matcher("$error"), 
				), 
			) 
		}) 
	}) 
	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_up"),
			)
			r.Match( 
				riemann.Group( 
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_name_and_capability", 
							hass.Entity("capability","val")
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					tts.Matcher("brightening the lights"), 
				), 
			) 
		}) 
	}) 
	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_up"),
				micSensor.Entities(
					"house_place","val"
				)
			)
			r.Match( 
				riemann.Group( 
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					tts.Matcher("There is no light called like that"), 
				), 
			) 
		}) 
	}) 
	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_up"),
				micSensor.Entities(
					"house_place","val"
				)
			)
			r.Match( 
				riemann.Group( 
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					iot.Matcher("resolve_by_domain_name_and_capability", 
							hass.Entity("capability","val")
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					tts.Matcher("$error"), 
				), 
			) 
		}) 
	}) 
	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_up"),
				micSensor.Entities(
					"house_place","val"
				)
			)
			r.Match( 
				riemann.Group( 
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					iot.Matcher("resolve_by_domain_name_and_capability", 
							hass.Entity("capability","val")
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					tts.Matcher("brightening the lights"), 
				), 
			) 
		}) 
	}) 
	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_up"),
				micSensor.Entities(
					"house_place","val"
				)
			)
			r.Match( 
				riemann.Group( 
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					tts.Matcher("There is no light called like that"), 
				), 
			) 
		}) 
	}) 
	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_up"),
				micSensor.Entities(
					"house_place","val"
				)
			)
			r.Match( 
				riemann.Group( 
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_name_and_capability", 
							hass.Entity("capability","val")
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					tts.Matcher("$error"), 
				), 
			) 
		}) 
	}) 
	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_up"),
				micSensor.Entities(
					"house_place","val"
				)
			)
			r.Match( 
				riemann.Group( 
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_name_and_capability", 
							hass.Entity("capability","val")
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					tts.Matcher("brightening the lights"), 
				), 
			) 
		}) 
	}) 
	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_up"),
				micSensor.Entities(
					"house_place","val"
				)
			)
			r.Match( 
				riemann.Group( 
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					tts.Matcher("There is no light called like that"), 
				), 
			) 
		}) 
	}) 
	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_up"),
				micSensor.Entities(
					"house_place","val"
				)
			)
			r.Match( 
				riemann.Group( 
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_name_and_capability", 
							hass.Entity("capability","val")
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					tts.Matcher("$error"), 
				), 
			) 
		}) 
	}) 
	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_up"),
				micSensor.Entities(
					"house_place","val"
				)
			)
			r.Match( 
				riemann.Group( 
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_name_and_capability", 
							hass.Entity("capability","val")
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					tts.Matcher("brightening the lights"), 
				), 
			) 
		}) 
	}) 
	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_down"),
			)
			r.Match( 
				riemann.Group( 
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					tts.Matcher("There is no light called like that"), 
				), 
			) 
		}) 
	}) 
	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_down"),
			)
			r.Match( 
				riemann.Group( 
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_name_and_capability", 
							hass.Entity("capability","val")
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					tts.Matcher("$error"), 
				), 
			) 
		}) 
	}) 
	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_down"),
			)
			r.Match( 
				riemann.Group( 
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_name_and_capability", 
							hass.Entity("capability","val")
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					tts.Matcher("dimming the lights"), 
				), 
			) 
		}) 
	}) 
	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_down"),
			)
			r.Match( 
				riemann.Group( 
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					tts.Matcher("There is no light called like that"), 
				), 
			) 
		}) 
	}) 
	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_down"),
			)
			r.Match( 
				riemann.Group( 
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_name_and_capability", 
							hass.Entity("capability","val")
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					tts.Matcher("$error"), 
				), 
			) 
		}) 
	}) 
	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_down"),
			)
			r.Match( 
				riemann.Group( 
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_name_and_capability", 
							hass.Entity("capability","val")
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					tts.Matcher("dimming the lights"), 
				), 
			) 
		}) 
	}) 
	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_down"),
				micSensor.Entities(
					"house_place","val"
				)
			)
			r.Match( 
				riemann.Group( 
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					tts.Matcher("There is no light called like that"), 
				), 
			) 
		}) 
	}) 
	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_down"),
				micSensor.Entities(
					"house_place","val"
				)
			)
			r.Match( 
				riemann.Group( 
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					iot.Matcher("resolve_by_domain_name_and_capability", 
							hass.Entity("capability","val")
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					tts.Matcher("$error"), 
				), 
			) 
		}) 
	}) 
	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_down"),
				micSensor.Entities(
					"house_place","val"
				)
			)
			r.Match( 
				riemann.Group( 
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					iot.Matcher("resolve_by_domain_name_and_capability", 
							hass.Entity("capability","val")
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					tts.Matcher("dimming the lights"), 
				), 
			) 
		}) 
	}) 
	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_down"),
				micSensor.Entities(
					"house_place","val"
				)
			)
			r.Match( 
				riemann.Group( 
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					tts.Matcher("There is no light called like that"), 
				), 
			) 
		}) 
	}) 
	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_down"),
				micSensor.Entities(
					"house_place","val"
				)
			)
			r.Match( 
				riemann.Group( 
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_name_and_capability", 
							hass.Entity("capability","val")
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					tts.Matcher("$error"), 
				), 
			) 
		}) 
	}) 
	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_down"),
				micSensor.Entities(
					"house_place","val"
				)
			)
			r.Match( 
				riemann.Group( 
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_name_and_capability", 
							hass.Entity("capability","val")
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					tts.Matcher("dimming the lights"), 
				), 
			) 
		}) 
	}) 
	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_down"),
				micSensor.Entities(
					"house_place","val"
				)
			)
			r.Match( 
				riemann.Group( 
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					tts.Matcher("There is no light called like that"), 
				), 
			) 
		}) 
	}) 
	Describe("User says ", func() { 
		It("Should say ", func() { 
			r.Sensors.Mic.SendVT(micSensor.WAKEUP) 
			r.WaitFor(olly).ToBe(riemann.Listening()) 
			r.Sensors.Mic.SendNlpResult( 
				micSensor.Domains("iot_lighting"),
				micSensor.Intents("iot_lighting:turn_down"),
				micSensor.Entities(
					"house_place","val"
				)
			)
			r.Match( 
				riemann.Group( 
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Matcher("set", 
							hass.Entity("duration","val")
							hass.Entity("token","val")
					)
					lights.Matcher("turn_on", 
							hass.Entity("entity_id","val")
							hass.Entity("brightness","val")
					)
					iot.Matcher("resolve_by_domain_and_name", 
							hass.Entity("domain","val")
							hass.Entity("name","val")
					)
					timeout.Mat